image: ghcr.io/davidhiendl/gitlab-runner-hetzner-autoscale:master
pullPolicy: Always
registrationToken: ""
ciServerUrl: "https://gitlab.com/"
hetznerApiToken: ""

resources:
  requests:
    cpu: "150m"
    memory: "250Mi"
  limits:
    cpu: "250m"
    memory: "500Mi"
